ARG GOLANG_IMAGE_TAG=1.20
FROM mcr.microsoft.com/oss/go/microsoft/golang:${GOLANG_IMAGE_TAG} as build
ARG TERRAFORM_DOCS_VERSION=v0.18.0
ARG TERRAGRUNT_VERSION=v0.43.0
ARG TFMOD_TEST_HELPER_VERSION=v0.0.22
ARG GOLANGCI_LINT_VERSION=v1.49.0
ARG HCLEDIT_VERSION=v0.2.6
ARG GOSEC_VERSION=v2.14.0
ARG TFENV=v3.0.0
ARG GREPT_VERSION=1a4f08c2fdc41b6a3702fa1238354c40a3fcce3e
ARG NEWRES_VERSION=a535fe92925845dfa033a3db71adf7d65511cbf3
ARG AVMFIX_VERSION=9c158444b055e845c0cc9afc7cdc88d0ab19e5eb
ARG HCLMERGE_VERSION=8735bef83162f3ee952213b16e89f8d0ac0d08f7
ARG PREVIOUS_TAG_VERSION=656b12a97270ca29998ad62e3564d08e7d4369ba
ARG CONFTEST_VERSION=v0.56.0
ARG MAPOTF_VERSION=34acfd616ae081a560286d06c42f1f8329cf5b74
ARG TARGETARCH
COPY GNUmakefile /src/GNUmakefile
COPY scripts /src/scripts
RUN cd /src && \
    apt-get update && \
    apt-get install -y zip  && \
    export CGO_ENABLED=0 && \
    # go install golang.org/x/tools/cmd/goimports@latest && \
    # go install mvdan.cc/gofumpt@latest && \
    # go install github.com/Azure/terraform-module-test-helper/bin/breaking_detect@$TFMOD_TEST_HELPER_VERSION && \
    # go install github.com/securego/gosec/v2/cmd/gosec@$GOSEC_VERSION && \
    # go install github.com/minamijoyo/hcledit@$HCLEDIT_VERSION && \
    # go install github.com/lonegunmanb/previousTag@$PREVIOUS_TAG_VERSION && \
    # go install github.com/magodo/hclgrep@latest && \
    # go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$GOLANGCI_LINT_VERSION && \
    # go install github.com/lonegunmanb/avmfix@$AVMFIX_VERSION && \
    # go install github.com/Azure/grept@$GREPT_VERSION && \
    # go install github.com/lonegunmanb/newres/v3@$NEWRES_VERSION && \
    # go install github.com/lonegunmanb/hclmerge@$HCLMERGE_VERSION && \
    # go install github.com/open-policy-agent/conftest@$CONFTEST_VERSION && \
    # go install github.com/terraform-docs/terraform-docs@$TERRAFORM_DOCS_VERSION && \
    go install github.com/Azure/mapotf@$MAPOTF_VERSION
    # cd /src && \
    # git clone https://github.com/lonegunmanb/tflintenv.git && \
    # cd tflintenv && cd tflintenv && go install && \
    # cd ../tflint && go install && \
    # cd /src && \
    # git clone https://github.com/lonegunmanb/terrafmt.git && \
    # cd terrafmt && \
    # go install && \
    # cd /src && \
    # git clone https://github.com/tfutils/tfenv.git && \
    # cd /src/tfenv && \
    # git checkout $TFENV && \
    # rm -rf .git && \
    # cd /src && \
    # git clone https://github.com/iamhsa/pkenv.git && \
    # cd pkenv && \
    # rm -rf .git
