name: 'Comment on PR'

permissions:
  contents: read
  pull-requests: read

on:
  workflow_run:
    workflows: ["Pre Pull Request Check"]
    types:
      - completed

jobs:
  comment:
    uses: Azure/tfmod-scaffold/.github/workflows/breaking-change-detect.yaml@main