name: Pre Pull Request Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'
      - '**/go.mod'

permissions:
  contents: read
  pull-requests: read

jobs:
  prepr-check:
    uses: Azure/tfmod-scaffold/.github/workflows/pr-check.yaml@main