name: Update Changelog
on:
  push:
    branches:
      - main
      - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: 8BitJonny/gh-get-current-pr@2.1.0
        id: PR
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true
          initial_version: 0.0.0
      - name: update-changelog
        if: steps.PR.outputs.number != ''
        run: |
          MAJOR_VERSION=$(ls | grep CHANGELOG |  cut -d'-' -f 2 | cut -f 1 -d '.' |  grep v | sort -V -r | head -n 1)
          if [ -z "$MAJOR_VERSION" ]; then
            MAJOR_VERSION=0
          fi
          MAJOR_VERSION=${MAJOR_VERSION#"v"}
          MAJOR_VERSION=$((MAJOR_VERSION+1))
          # if latest tag is 2.6.0 and current unreleased major version is 3.0.0, use 2.6.0; if current major version is 2.0.0 and latest tag is 2.6.0, use 2.0.0
          VERSION=$(printf '$MAJOR_VERSION.0.0\n${{ steps.get-latest-tag.outputs.tag }}\n' | sort -V | head -n 1)
          docker run --rm -v $(pwd):/src -w /src githubchangeloggenerator/github-changelog-generator -u ${{ github.repository_owner }} -p ${{ github.event.repository.name }} -t ${{ secrets.GITHUB_TOKEN }} --no-issues --no-compare-link --since-tag $VERSION
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog