name: AVM makefile

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  makefile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: makefile
        run: |
          make -f avmmakefile help
