name: 'Comment on PR'

on:
  workflow_call:

jobs:
  comment:
    name: 'breaking change detect'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: 'Download change artifact'
        uses: dawidd6/action-download-artifact@268677152d06ba59fcec7a7f0b5d961b6ccd7e1e # v2.28.0
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          run_id: ${{ github.event.workflow_run.id }}
          workflow: pr-check.yaml
          name: change
          if_no_artifact_found: ignore
      - name: Check change existence
        id: check_change
        uses: andstor/file-existence-action@f02338908d150e00a4b8bebc2dad18bd9e5229b0 # v1.1.0
        with:
          files: "change"
      - name: 'Comment on PR'
        if: steps.check_change.outputs.files_exists == 'true'
        run: |
          export PR_NUMBER=$(cat change | jq -r '.pr')
          msg=$(cat change | jq -r '.body')
          jq -n --arg msg "$msg" '{body: $msg}' > body.txt
          curl -s -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments -d @body.txt