name: 'Comment on PR'

on:
  workflow_call:

jobs:
  comment:
    name: 'breaking change detect'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: 'Bypass detect'
        run: |
          echo "bypass detect"
