name: Build Docker Image

on:
  push:
    tags:
      - v*

env:
  APP_NAME: tfmodule-localrunner
  DOCKERHUB_REPO: ${{ secrets.DOCKER_SERVER_URL }}/public/azterraform

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Use Temporary Disk as Docker Path
        run: |
          sudo service docker stop
          cd /var/lib
          sudo rm -rf docker
      - name: Maximize build space
        uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c #v10
        with:
          root-reserve-mb: 1024
          swap-size-mb: 1024
          build-mount-path: '/var/lib/docker'
      - name: Restart Docker
        run: |
          sudo service docker start
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
      - name: Read version.env
        id: readenv
        uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b # v1.1.6
        with:
          path: ./version.env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
      - name: Login to DockerHub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ${{ secrets.DOCKER_SERVER_URL }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      - name: Set up local registry
        run: docker run -d -p 5000:5000 --restart=always --name registry registry:2
      - name: Local builder image
        id: docker_build_builder
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          file: ./Dockerfile_builder
          tags: localhost:5000/builder:latest
          build-args: |
            ${{ steps.readenv.outputs.content }}
      - name: Build and push azterraform
        id: docker_build_azterraform
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}
          build-args: |
            ${{ steps.readenv.outputs.content }}